# commands for setting up the container


# Copy the scripts into the container
COPY ./py_app /code
COPY ./common_py /code
COPY ./bash_scripts /code
COPY ./common_scripts /code

ENTRYPOINT ["/code/main.sh"]

